version: '3.8'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: uno2tres
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - '3307'
    

volumes:
  db_data:
